services:
  frontend:
    container_name: knowflow-frontend
    image: zxwei/knowflow-web:v0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=/api 
    networks:
      - management_network

  backend:
    container_name: knowflow-backend
    image: zxwei/knowflow-server:v0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: backend

    ports:
      - "5000:5000"
    environment:
      - RAGFLOW_API_KEY=${RAGFLOW_API_KEY}
      - RAGFLOW_BASE_URL=${RAGFLOW_BASE_URL}
      - DB_HOST=${DB_HOST}
      - MINIO_HOST=${MINIO_HOST}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - MINERU_MODLES_DIR=${MINERU_MODLES_DIR}
      - FLASK_ENV=development
      - CORS_ALLOWED_ORIGINS=http://frontend
      - MANAGEMENT_ADMIN_USERNAME=${MANAGEMENT_ADMIN_USERNAME:-admin}
      - MANAGEMENT_ADMIN_PASSWORD=${MANAGEMENT_ADMIN_PASSWORD:-12345678}
      - MANAGEMENT_JWT_SECRET=${MANAGEMENT_JWT_SECRET:-12345678}
    volumes:
      - ${MINERU_MODLES_DIR}:/root/.cache/huggingface/hub
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - management_network

networks:
  management_network:
    driver: bridge


  